# Generated by Django 5.1.3 on 2024-11-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
